# Generated by Django 3.0.2 on 2020-10-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('re_enter', models.CharField(max_length=100)),
            ],
        ),
    ]
