# Generated by Django 3.0.2 on 2020-10-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(default=False)),
                ('checkout', models.DateTimeField(default=False)),
                ('singleBHK', models.BooleanField()),
                ('doubleBHK', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
